name = "Cristobal Valencia Ceron!"
rol = "Backend Developer"
email = "cristobalvalencia3002@gmail.com"
phone = "+57 (300) 541-2940"
birthday = "Marzo 26, 2003"
location = "Cali, Valle del Cauca, Colombia"
avatar = "./config/assets/avatars/my-photo.png"
username = "DevCristobalvc" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd" 
presentation = """
A los 20 años, he descubierto mi pasión por el desarrollo de software. Mi principal objetivo es contribuir al avance tecnológico de mi país.

He adquirido conocimientos de manera autodidacta y complementándolos con certificaciones mientras estudio ingeniería. Actualmente, soy contratista del estado y funcionario del SENA, trabajando a tiempo completo en el área administrativa con el propósito de implementar herramientas que mejoren la eficiencia del servicio que brindamos.
"""
